org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

minecraft_version=26.2
minecraft_version_range=[26.2]
neo_version=26.2.0.59

mod_id=kokoto_webchat
mod_name=KOKOTO WebChat
mod_license=MIT
mod_version=5.3.1
mod_group_id=dev.kokoto.webchat
archives_base_name=KOKOTO-WebChat-NeoForge
